- hosts: 127.0.0.1
  vars:
    my_unsafe_variable: !unsafe 'unsafe value'

    my_unsafe_array:
     - !unsafe 'unsafe element'
     - 'safe element'

    my_unsafe_hash:
     unsafe_key: !unsafe 'unsafe value'

    app1:
      jvm: &jvm_opts
        opts: '-Xms1G -Xmx2G'
        port: 1000
        path: /usr/lib/app1
    app2:
        jvm:
          <<: *jvm_opts
          path: /usr/lib/app2
#Here, app1 and app2 share the values for opts and port using the anchor
#&jvm_opts and the alias *jvm_opts. The value for path is merged by << or merge operator.
    webapp:
        version: &my_version 1.0
        custom_name:
            - "ToDo_App"
            - *my_version
  tasks:
    - name: Using Anchor value
      debug:
        msg: My app is called "{{ webapp.custom_name | join('-') }}".
