---
#- import_playbook: connectserver.yml
- name: Install mysql, nginx and httpd software
  hosts: agentnode
  remote_user: root
  gather_facts: no
  vars_files:
    - ./vars/variable.yml

  vars:
    packag:
        - name: nginx
          required: True
#        - name: mysql
#          required: True
        - name: httpd
          required: True

  tasks:
    - name: Include varaible names
#      include_vars:
#        file: ./vars/variable.yml
    - name: Install {{ item }} in RHEL
      yum:
        name: '{{ item.name }}'
        state: present
      when: item.required == True
      loop: "{{ packag }}"
#    - name: Install nginx in RHEL
#      yum:
#        name: nginx
#        state: present
#    - name: Ensure service running
#      service:
#        name: '{{ item.name }}'
#        state: started
#      when: item.required == True
#      loop: "{{ packages }}"
  tasks:
    - name: Nginx template files to parse {{ ansible_facts }}
      template:
        src: ./templates/default.j2
        dest: /etc/nginx/conf.d/default.conf
#      vars:
#        nginx_port: "{{ nginx_port }}"
    - name: httpd template files to parse
      template:
        src: ../templates/httpd.j2
        dest: /etc/httpd/conf/httpd.conf
      vars:
#        httpd_port: 8886 #"{{ httpd_port }}"
    - name:
      copy:
        src: README.md
        dest: /etc/nginx
    - debug:
        msg: "Print the details"
    - name: Nginx Restart
      service:
        name: nginx
        state: reloaded
    - name: httpd Restart
      service:
        name: httpd
        state: reloaded
    - name: Enable nginx service on reboot
      service:
        name: nginx
        enabled: yes
    - name: Enable Apache service on reboot
      service:
        name: httpd
        enabled: yes
#      notify:
#        - restart httpd
#        - restart nginx

#  tasks:
#    - name: Print or get working directory
#      command: pwd
...
